#!/bin/bash
case $(pmset -g batt | tail -1 | awk "{ print \$3 }" | tr -d ";") in
    discharging)
        echo "✘"
    ;;
    charging)
        echo "ϟ"
    ;;
    charged)
        echo "✔"
    ;;
esac
